# Generated by Django 5.1.4 on 2024-12-21 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_travelservice_remove_payment_booking_remove_seat_bus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelservice',
            name='available_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='travelservice',
            name='total_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.travelservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
