# Generated by Django 5.1.4 on 2024-12-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='TravelService',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
