# Generated by Django 5.1.4 on 2024-12-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0005_remove_booking_travel_service_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_description', models.TextField()),
                ('departure_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('total_time', models.FloatField()),
                ('start_time', models.TimeField()),
                ('arival_time', models.TimeField()),
                ('journey_date', models.DateField()),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('Non AC', 'Non AC')], max_length=10)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nid', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_start_time', models.TimeField()),
                ('trip_arrival_time', models.TimeField()),
                ('journey_date', models.DateField()),
                ('seats_booked', models.CharField(max_length=255)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('bus_book_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_phone', models.CharField(max_length=14)),
                ('selected_seats', models.CharField(max_length=200)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
