# Generated by Django 5.1.4 on 2024-12-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='total_price',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
