# Generated by Django 5.1.4 on 2024-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_busbooking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('plane_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plane_name', models.CharField(max_length=255)),
                ('bus_description', models.TextField()),
                ('departure_airport', models.CharField(max_length=255)),
                ('destination_airport', models.CharField(max_length=255)),
                ('total_time', models.FloatField()),
                ('start_time', models.TimeField()),
                ('arival_time', models.TimeField()),
                ('journey_date', models.DateField()),
                ('p_total_seats', models.IntegerField()),
                ('p_available_seats', models.IntegerField()),
                ('p_fare', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
