# Generated by Django 5.1.4 on 2024-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_busbooking_bus_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=255)),
                ('departure_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('arival_time', models.TimeField()),
                ('journey_date', models.DateField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=15)),
                ('selected_seats', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='busbooking',
            old_name='bus',
            new_name='bus_name',
        ),
    ]
