# Generated by Django 5.1.4 on 2024-12-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_car_events_hotel_launch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='bus_name',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='user',
        ),
    ]
