# Generated by Django 5.1.4 on 2024-12-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_busbooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='bus',
            field=models.ForeignKey(default=13201, on_delete=django.db.models.deletion.CASCADE, to='myapp.bus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
