# Generated by Django 5.1.4 on 2024-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_busbooking_bus_busbooking_bus_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='bus_book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
