# Generated by Django 5.1.4 on 2024-12-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_busbooking_id_alter_busbooking_bus_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='bus_book_id',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
