# Generated by Django 5.1.4 on 2024-12-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_busbooking_bus_book_id_busbooking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Paid', max_length=10),
        ),
    ]
