# Generated by Django 5.1.4 on 2025-01-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_busbooking_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air',
            old_name='bus_description',
            new_name='plane_description',
        ),
    ]
