# Generated by Django 5.1.4 on 2025-01-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_bus_description_air_plane_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='plane_description',
        ),
    ]
