# Generated by Django 5.1.4 on 2025-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_air_plane_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('park_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('park_name', models.CharField(max_length=255)),
                ('park_location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('fare', models.IntegerField()),
            ],
        ),
    ]
